### PR TITLE
Add animation cache and fix torque in animations

### PR DESCRIPTION
**Pull request by timonegk**
## Proposed changes
This PR includes two changes:
1. Add a cache to animations so that the json files are not read every time again
2. Fix torque reading, currently the torque value of the last keyframe is used for all keyframes

## Related issues
This touches #208, but reads the animation when it is used for the first time because we have no way of knowing which animations will be used. Should we just load all animations? Or specify a list in the config file?

## Necessary checks
- [x] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [x] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

### CODE REVIEW

**Comment by SammyRamone** [comment]
I pro loading all animations in wolfgang_animations. There are not so many and having to load it on the first execution is not really optimal

**Comment by timonegk** [comment]
All animations are now loaded during the startup.

**Comment by timonegk** [comment]
I also adapted the code to our code style.

**Review by 16stelter — APPROVED** [review]
lgtm

**Pull request merged**
