### PR TITLE
add final stabilizing to kick

### PR DESCRIPTION
**Pull request by timonegk**
## Proposed changes
Adds stabilizing with imu after the kick.

## Necessary checks
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

### CODE REVIEW

**Review by SammyRamone — APPROVED** [review]

**Comment by SammyRamone** [comment]
fixes https://github.com/bit-bots/bitbots_motion/issues/235

**Comment by jaagut** [comment]
@timonegk what's the status of this PR? Is this still needed?

**Comment by jaagut** [comment]
@timonegk Ping

**Comment by timonegk** [comment]
We don't know, we have to put some work into the kick. This can probably be closed for now and we will reevaluate which parts we need and which we don't need.

**Pull request closed without merging**
