### PR TITLE
Upgrade to tf2

### PR DESCRIPTION
**Pull request by timonegk**
Now after the Walking Refactor in #18 another try of migrating to tf2 as tf is deprecated since ROS Hydro. This has been tested in rviz but not on the real robot yet.

### CODE REVIEW

**Comment by timonegk** [comment]
This would also allow us to use the upstream version of BioIK instead of our fork

**Comment by SammyRamone** [comment]
was it tested on the robot yet?

**Comment by timonegk** [comment]
It was not, and the dynamic kick and dynup must also be included. We also have to see whether this or #46 should be merged first because they partially change the same files

**Comment by ftsell** [comment]
Since there is another walking refactor underway in #46 I would rather redo this pull request or implement it there directly

**Comment by timonegk** [comment]
I redid this for the refactored walking, dynup and dynamic kick. It has been tested in visualization and on the robot.

**Comment by ftsell** [comment]
I am wondering how you were able to test this since it does not compile for me. We'll have to take a look at it tomorrow

**Comment by timonegk** [comment]
> it does not compile for me

Sorry, I forgot to tell you that you have to go one commit back (i.e. to the upstream master instead of our fork) in `bio_ik` and `bio_ik_service`.

> please add appropriate dependencies to `bitbots_dynup/package.xml`

Done in 54dc6990278ce197d36601549dbed02ea5f66594.

**Pull request merged**
