### PR TITLE
dynup stabilizer to fused

### PR DESCRIPTION
**Pull request by SammyRamone**
## Proposed changes
Small fix + change to fused angles

## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

### CODE REVIEW

**Review by 16stelter — APPROVED** [review]
lgtm

**Comment by jgueldenstein** [comment]
I tested this in the webots simulation. The following issues occured:

Previously the robot would go into the walkready pose from the zero position when starting the motion. This does not happen anymore, but it stays in the zero position.
This may not be an issue in simulation if we set the initial positions to the walkready (TODO) but in the real world.

Standing up from front works relatively well, it previously almost never did.

Standing up from the back does not work anymore where it did previously in 1/2 or 1/3 cases.

**Review by jgueldenstein — APPROVED** [review]
Seems to be working correctly, wait with merge until we have the optimized parameters

**Review by timonegk — APPROVED** [review]
Works from back, doesn't work from front – so it is not worse than the current master and we can merge it.

**Pull request merged**
